[package]
name = "game_backend"
version = "0.1.0"
authors = ["USUARIO <william.usp@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
